import { useEffect, useState } from 'react';

const STORAGE_KEY = 'smp-sheet-directories-v1';
const DEFAULT_DIRECTIONS = ['внутримышечно', 'внутривенно', 'подкожно', 'сублингвально'];

const DEFAULT_DRUGS = [
  ['Dopamini','Sol. Dopamini'],['Phenylephrini','Sol. Phenylephrini'],['Epinephrini','Sol. Epinephrini'],['Norepinephrini','Sol. Norepinephrini'],
  ['Carbonis activati','Tab. Carbonis activati'],['Nitroglycerini','Tab. Nitroglycerini'],['Procainamidi','Sol. Procainamidi'],['Verapamili','Sol. Verapamili'],['Amiodaroni','Sol. Amiodaroni'],['Propranololi','Tab. Propranololi'],['Lidocaini','Sol. Lidocaini'],['Metoprololi','Sol. Metoprololi / Tab. Metoprololi'],
  ['Diphenhydramini','Sol. Diphenhydramini'],['Chloropyramini','Sol. Chloropyramini'],['Calcii gluconatis','Sol. Calcii gluconatis'],['Povidoni iodi','Sol. Povidoni iodi'],['Hydrogenii peroxydi','Sol. Hydrogenii peroxydi'],['Kalii permanganatis','Sol. Kalii permanganatis'],['Atropini','Sol. Atropini'],
  ['Salbutamoli','Aerosolum Salbutamoli'],['Budesonidi','Pulvis / suspensio Budesonidi'],['Aminophyllini','Sol. Aminophyllini'],['Acidi ascorbinici','Sol. Acidi ascorbinici'],['Pyridoxini','Sol. Pyridoxini'],['Thiamini','Sol. Thiamini'],
  ['Clonidini','Sol. Clonidini'],['Nifedipini','Tab. Nifedipini'],['Captoprili','Tab. Captoprili'],['Insulini asparti','Sol. Insulini asparti'],['Hydrocortisoni','Lyophilisatum Hydrocortisoni'],['Dexamethasoni','Sol. Dexamethasoni'],['Oxytocini','Sol. Oxytocini'],['Prednisoloni','Sol. Prednisoloni'],
  ['Dextranum','Sol. Dextranum'],['Hydroxyethylamylum','Sol. Hydroxyethylamylum'],['Natrii chloridi','Sol. Natrii chloridi'],['Dextrosi','Sol. Dextrosi'],['Natrii acetatis + Natrii chloridi + Kalii chloridi','Sol. Natrii acetatis + Natrii chloridi + Kalii chloridi'],['Solutio Natrii lactatis complexa','Sol. Natrii lactatis complexa'],['Kalii chloridi','Sol. Kalii chloridi'],['Natrii hydrocarbonatis','Sol. Natrii hydrocarbonatis'],
  ['Procaini','Sol. Procaini'],['Suxamethonii chloridi et iodidi','Sol. Suxamethonii chloridi et iodidi'],['Pipecuronii bromidi','Lyophilisatum Pipecuronii bromidi'],['Furosemidi','Sol. Furosemidi'],['Morphini','Sol. Morphini'],['Trimeperidini','Sol. Trimeperidini'],['Fentanyli','Sol. Fentanyli'],['Tramadoli','Sol. Tramadoli'],
  ['Ketorolaci','Sol. Ketorolaci'],['Paracetamoli','Sol. Paracetamoli'],['Ketoprofeni','Sol. Ketoprofeni'],['Chlorpromazini','Sol. Chlorpromazini'],['Droperidoli','Sol. Droperidoli'],['Midazolami','Sol. Midazolami'],['Naloxoni','Sol. Naloxoni'],['Natrii thiosulfatis','Sol. Natrii thiosulfatis'],['Protamini sulfatis','Sol. Protamine sulfatis'],['Diazepami','Sol. Diazepami'],['Digoxini','Sol. Digoxini'],['Drotaverini','Sol. Drotaverini'],['Magnesii sulfatis','Sol. Magnesii sulfatis'],['Platyphyllini','Sol. Platyphyllini'],['Coffeini','Sol. Coffeini'],['Ethanoli','Sol. Ethanoli'],
  ['Acidi aminocapronici','Sol. Acidi aminocapronici'],['Acidi acetylsalicylici','Tab. Acidi acetylsalicylici'],['Heparini natrii','Sol. Heparini natrii'],['Clopidogreli','Tab. Clopidogreli'],['Etamsylati','Sol. Etamsylati'],['Dinitrogenii oxydi','Gas compressus'],['Ketamini','Sol. Ketamini'],['Propofoli','Emulsio Propofoli'],['Thiopentali natrii','Lyophilisatum Thiopentali natrii'],['Alteplasi','Lyophilisatum Alteplasi'],['Prourokinasi','Lyophilisatum Prourokinasi'],['Citicolini','Sol. Citicolini'],['Glycini','Tab. Glycini'],
  ['Ethylmethylhydroxypyridini succinatis','Sol. Ethylmethylhydroxypyridini succinatis'],['Metoclopramidi','Sol. Metoclopramidi'],['Ondansetroni','Sol. Ondansetroni'],['Kalii et Magnesii asparaginatis','Sol. Kalii et Magnesii asparaginatis'],['Aquae pro injectionibus','Aqua pro injectionibus'],['Acidi succinici + Inosini + Nicotinamidi + Riboflavini mononucleotidi','Sol. composita'],['Chloramphenicoli','Tab. Chloramphenicoli'],['Streptomycini','Pulvis Streptomycini'],['Ciprofloxacini','Tab. Ciprofloxacini / Sol. Ciprofloxacini'],['Ceftriaxoni','Pulvis Ceftriaxoni'],['Amoxicillini','Tab. Amoxicillini'],['Methionyl-glutaminyl-histidyl-phenylalanyl-prolyl-glycyl-prolyl','Guttae nasales']
].map(([name,dose], i) => ({ id: `default-${i}`, name, dose, route: '' }));

function loadData() {
  try {
    const saved = JSON.parse(localStorage.getItem(STORAGE_KEY));
    return { drugs: Array.isArray(saved?.drugs) && saved.drugs.length ? saved.drugs : DEFAULT_DRUGS, organizations: Array.isArray(saved?.organizations) ? saved.organizations : [] };
  } catch { return { drugs: DEFAULT_DRUGS, organizations: [] }; }
}
export function getDirectoryData() { return loadData(); }
export function saveDirectoryData(data) { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); window.dispatchEvent(new Event('smp-directories-updated')); }
export function suggestDirections(query) { const q=query.trim().toLowerCase().replace(/ё/g,'е'); if(!q) return []; return DEFAULT_DIRECTIONS.filter(x=>x.includes(q)); }

export default function DirectoryManager({ open, onClose }) {
  const [tab,setTab]=useState('drugs'); const [data,setData]=useState(loadData); const [drug,setDrug]=useState({name:'',dose:'',route:''}); const [organization,setOrganization]=useState('');
  useEffect(()=>{ if(open) setData(loadData()); },[open]); if(!open) return null;
  const persist=next=>{setData(next);saveDirectoryData(next);};
  const addDrug=e=>{e.preventDefault();if(!drug.name.trim())return;persist({...data,drugs:[...data.drugs,{id:Date.now(),...drug,name:drug.name.trim(),dose:drug.dose.trim(),route:drug.route.trim()}]});setDrug({name:'',dose:'',route:''});};
  const addOrganization=e=>{e.preventDefault();if(!organization.trim())return;persist({...data,organizations:[...data.organizations,{id:Date.now(),name:organization.trim()}]});setOrganization('');};
  return <div className="directory-overlay" onMouseDown={onClose}><div className="directory-modal" onMouseDown={e=>e.stopPropagation()}><div className="directory-head"><div><h2>Справочники</h2><p>Лекарства и медицинские организации сохраняются на этом устройстве.</p></div><button type="button" onClick={onClose}>×</button></div><div className="directory-tabs"><button className={tab==='drugs'?'active':''} onClick={()=>setTab('drugs')}>💊 Лекарства</button><button className={tab==='organizations'?'active':''} onClick={()=>setTab('organizations')}>🏥 Медорганизации</button></div>{tab==='drugs'?<><form className="directory-form" onSubmit={addDrug}><label><span>Название на латыни</span><input value={drug.name} onChange={e=>setDrug({...drug,name:e.target.value})} placeholder="Sol. Metamizoli"/></label><label><span>Дозировка / форма</span><input value={drug.dose} onChange={e=>setDrug({...drug,dose:e.target.value})} placeholder="1% — 1,0"/></label><label><span>Путь введения</span><input list="route-suggestions" value={drug.route} onChange={e=>setDrug({...drug,route:e.target.value})} placeholder="Начните писать: подк..."/><datalist id="route-suggestions">{DEFAULT_DIRECTIONS.map(x=><option key={x} value={x}/>)}</datalist></label><button className="directory-add" type="submit">Добавить препарат</button></form><div className="directory-list">{data.drugs.map(item=><div className="directory-item" key={item.id}><div><strong>{item.name}</strong><span>{item.dose}{item.dose&&item.route?' · ':''}{item.route}</span></div>{!String(item.id).startsWith('default-')&&<button type="button" onClick={()=>persist({...data,drugs:data.drugs.filter(x=>x.id!==item.id)})}>Удалить</button>}</div>)}</div></>:<><form className="directory-form organization-form" onSubmit={addOrganization}><label><span>Название медицинской организации</span><input value={organization} onChange={e=>setOrganization(e.target.value)} placeholder="ГБУЗ РБ Туймазинская ЦРБ"/></label><button className="directory-add" type="submit">Добавить организацию</button></form><div className="directory-list">{data.organizations.map(item=><div className="directory-item" key={item.id}><strong>{item.name}</strong><button type="button" onClick={()=>persist({...data,organizations:data.organizations.filter(x=>x.id!==item.id)})}>Удалить</button></div>)}</div></>}</div></div>;
}
