import { useMemo, useState } from 'react';
import { ClipboardList, Printer, RotateCcw, Settings, Stethoscope } from 'lucide-react';
import PrintSheet from './components/PrintSheet';
import DateWheelPicker from './components/DateWheelPicker';
import DiagnosisPicker from './components/DiagnosisPicker';
import DirectoryManager from './components/DirectoryManager';
import HelpAutocomplete from './components/HelpAutocomplete';
import { OrganizationPicker } from './components/DirectoryPicker';

const todayISO = () => new Date().toISOString().slice(0, 10);
const initialForm = { sheetNumber: '', surname: '', name: '', patronymic: '', birthDate: '', ageYears: '', ageMonths: '', sex: '', document: '', address: '', scene: '', sameAddress: false, diagnosis: '', circumstances: '', callDate: todayISO(), callTime: '', help: '', bloodPressure: '', temperature: '', glucose: '', lams: '', saturation: '', hospital: '', deliveryDate: todayISO(), deliveryTime: '', transport: '', stationDoctor: '', team: '', brigadeDoctor: '', notes: '' };
function Field({ label, name, value, onChange, type = 'text', placeholder = '', wide = false, readOnly = false }) { return <label className={wide ? 'field field-wide' : 'field'}><span>{label}</span><input name={name} type={type} value={value} onChange={onChange} placeholder={placeholder} readOnly={readOnly} /></label>; }
function TextField({ label, name, value, onChange, rows = 3 }) { return <label className="field field-wide"><span>{label}</span><textarea name={name} rows={rows} value={value} onChange={onChange} /></label>; }
function calculateAge(birthDate) { if (!birthDate) return { years: '', months: '' }; const [year, month, day] = birthDate.split('-').map(Number); if (!year || !month || !day) return { years: '', months: '' }; const today = new Date(); let years = today.getFullYear() - year; let months = today.getMonth() + 1 - month; if (today.getDate() - day < 0) months -= 1; if (months < 0) { years -= 1; months += 12; } if (years < 0) return { years: '', months: '' }; return { years, months }; }
function formatBloodPressure(value) { const digits = value.replace(/\D/g, '').slice(0, 6); if (digits.length <= 3) return digits; return `${digits.slice(0, 3)}/${digits.slice(3)}`; }
function formatTemperature(value) { const digits = value.replace(/\D/g, '').slice(0, 3); if (digits.length < 3) return digits; return `${digits.slice(0, -1)},${digits.slice(-1)}`; }
function formatGlucose(value) { const digits = value.replace(/\D/g, '').slice(0, 3); if (digits.length < 2) return digits; const number = Number(digits) / 10; return Number.isInteger(number) ? `${number},0` : String(number).replace('.', ','); }
function formatName(value) { return value.replace(/(^|[\s-])([А-Яа-яЁё])/g, (_, prefix, letter) => `${prefix}${letter.toUpperCase()}`); }
function formatTime(value) { const digits = value.replace(/\D/g, '').slice(0, 4); if (digits.length <= 2) return digits; return `${digits.slice(0, 2)}:${digits.slice(2)}`; }
function TimeField({ label, name, value, onChange }) { return <label className="field"><span>{label}</span><input name={name} type="text" inputMode="numeric" pattern="[0-9:]*" value={value} onChange={onChange} placeholder="Укажите время" /></label>; }
export default function App() {
  const [form, setForm] = useState(initialForm); const [directoriesOpen, setDirectoriesOpen] = useState(false);
  const hasStroke = useMemo(() => /инсульт|ОНМК|ишемическ|геморрагическ/i.test(form.diagnosis), [form.diagnosis]);
  const update = (event) => { const { name, value, type, checked } = event.target; setForm(prev => { if (name === 'sameAddress') return { ...prev, sameAddress: checked, scene: checked ? prev.address : prev.scene }; if (name === 'address' && prev.sameAddress) return { ...prev, address: value, scene: value }; if (name === 'bloodPressure') return { ...prev, bloodPressure: formatBloodPressure(value) }; if (name === 'temperature') return { ...prev, temperature: formatTemperature(value) }; if (name === 'glucose') return { ...prev, glucose: formatGlucose(value) }; if (name === 'surname' || name === 'name' || name === 'patronymic') return { ...prev, [name]: formatName(value) }; if (name === 'callTime' || name === 'deliveryTime') return { ...prev, [name]: formatTime(value) }; return { ...prev, [name]: type === 'checkbox' ? checked : value }; }); };
  const updateBirthDate = value => { const age = calculateAge(value); setForm(prev => ({ ...prev, birthDate: value, ageYears: age.years === '' ? '' : String(age.years), ageMonths: age.months === '' ? '' : String(age.months) })); };
  const reset = () => setForm({ ...initialForm, callDate: todayISO(), deliveryDate: todayISO() });
  return <div className="app-shell"><div className="screen-ui"><header className="topbar"><div className="brand"><div className="brand-icon"><Stethoscope size={22} /></div><div><strong>Сопроводительный лист СМП</strong><small>Электронная форма • проект Smp-sheet</small></div></div><div className="actions"><button className="secondary" type="button" onClick={() => setDirectoriesOpen(true)}><Settings size={17} /> Справочники</button><button className="secondary" type="button" onClick={reset}><RotateCcw size={17} /> Очистить</button><button className="primary" type="button" onClick={() => window.print()}><Printer size={17} /> Печать</button></div></header><main className="workspace">
    <section className="intro"><div><p className="eyebrow">СОПРОВОДИТЕЛЬНЫЙ ЛИСТ И ТАЛОН К НЕМУ</p><h1>Заполнение листа</h1><p>Данные вводятся один раз, а печатная версия автоматически формируется в виде двух сторон А4.</p></div><div className="status"><ClipboardList size={18} /> Черновик</div></section>
    <section className="card"><div className="section-head"><span className="number">1</span><div><h2>Пациент</h2><p>Основные сведения из пунктов 1–8 оригинального бланка.</p></div></div><div className="grid three"><Field label="№ сопроводительного листа" name="sheetNumber" value={form.sheetNumber} onChange={update} placeholder="Введите номер вручную"/><Field label="Фамилия" name="surname" value={form.surname} onChange={update}/><Field label="Имя" name="name" value={form.name} onChange={update}/><Field label="Отчество" name="patronymic" value={form.patronymic} onChange={update}/><DateWheelPicker value={form.birthDate} onChange={updateBirthDate}/><Field label="Возраст, лет" name="ageYears" value={form.ageYears} onChange={update} type="number" readOnly/><Field label="Возраст, месяцев" name="ageMonths" value={form.ageMonths} onChange={update} type="number" readOnly/><label className="field"><span>Пол</span><select name="sex" value={form.sex} onChange={update}><option value="">Не выбран</option><option>мужской</option><option>женский</option></select></label><Field label="Серия и номер документа" name="document" value={form.document} onChange={update} wide/><Field label="Место жительства" name="address" value={form.address} onChange={update} wide/><div className="field field-wide"><span>Место оказания СМП</span><input name="scene" type="text" value={form.scene} onChange={update} placeholder={form.sameAddress ? 'Совпадает с местом жительства' : ''} readOnly={form.sameAddress}/></div><label className="same-address"><input name="sameAddress" type="checkbox" checked={form.sameAddress} onChange={update}/> <span>Совпадает с местом жительства</span></label></div></section>
    <section className="card"><div className="section-head"><span className="number">2</span><div><h2>Состояние и помощь</h2><p>Диагноз, обстоятельства, медицинская помощь и дополнительные показатели.</p></div></div><div className="vitals"><Field label="АД, мм рт. ст." name="bloodPressure" value={form.bloodPressure} onChange={update} placeholder="12080"/><Field label="Температура, °C" name="temperature" value={form.temperature} onChange={update} placeholder="368"/><Field label="Глюкоза, ммоль/л" name="glucose" value={form.glucose} onChange={update} placeholder="5,4"/><Field label="Сатурация, %" name="saturation" value={form.saturation} onChange={update} type="number" placeholder="98"/><Field label="LAMS, баллы" name="lams" value={form.lams} onChange={update} type="number" placeholder="98"/></div>{hasStroke && <div className="notice">Обнаружены признаки инсульта/ОНМК — перед печатью проверьте LAMS, глюкозу и сатурацию.</div>}<div className="grid two"><DiagnosisPicker value={form.diagnosis} onChange={update}/><TextField label="Обстоятельства заболевания / несчастного случая" name="circumstances" value={form.circumstances} onChange={update} rows={4}/><label className="field field-wide"><span>Оказанная медицинская помощь</span><HelpAutocomplete value={form.help} onChange={value => setForm(prev => ({ ...prev, help: value }))}/></label><Field label="Дата принятия вызова" name="callDate" value={form.callDate} onChange={update} type="date"/><TimeField label="Время принятия вызова" name="callTime" value={form.callTime} onChange={update}/></div></section>
    <section className="card"><div className="section-head"><span className="number">3</span><div><h2>Доставка и передача</h2><p>Сведения о стационаре, транспортировке и бригаде.</p></div></div><div className="grid two"><OrganizationPicker value={form.hospital} onChange={update}/><Field label="Дата доставки" name="deliveryDate" value={form.deliveryDate} onChange={update} type="date"/><TimeField label="Время доставки" name="deliveryTime" value={form.deliveryTime} onChange={update}/><label className="field"><span>Способ транспортировки</span><select name="transport" value={form.transport} onChange={update}><option value="">Не выбран</option><option value="на носилках">На носилках</option><option value="на руках">На руках</option><option value="пешком">Пешком</option></select></label><Field label="Врач / фельдшер бригады" name="brigadeDoctor" value={form.brigadeDoctor} onChange={update}/><Field label="Фельдшер / врач принимающего отделения" name="stationDoctor" value={form.stationDoctor} onChange={update}/><Field label="Состав бригады" name="team" value={form.team} onChange={update}/></div><TextField label="Примечания" name="notes" value={form.notes} onChange={update} rows={4}/></section>
    <section className="next-step"><strong>Печать</strong><span>Кнопка «Печать» формирует две страницы А4: лицевая сторона с I и II экземплярами и оборотная сторона с пунктами 14–22.</span></section>
  </main></div><PrintSheet form={form}/><DirectoryManager open={directoriesOpen} onClose={() => setDirectoriesOpen(false)}/></div>;
}
